services:
  mongodb:
    image: mongo:7
    container_name: saec-mongo
    ports:
      - '9090:27017'
    volumes:
      - ./data:/data/db
    networks:
      - website-internal
    restart: unless-stopped

networks:
  website-internal:
    external: true
